"""Frozen lexical statistics and an acquisition head independent of content identity."""

import re


def fts_name(snapshot_id):
    if not re.fullmatch(r"N[0-9a-f]{64}", snapshot_id):
        raise ValueError("Invalid snapshot identifier")
    return "fts_" + snapshot_id[1:]


def freeze_fts(store, snapshot_id):
    name = fts_name(snapshot_id)
    exists = store.db.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (name,)).fetchone()
    if not exists:
        # Identifier is generated by this module from validated content-addressed IDs.
        store.db.execute(
            f"CREATE VIRTUAL TABLE {name} USING fts5(segment_id UNINDEXED,text,tokenize='unicode61 remove_diacritics 2')"
        )
        store.db.execute(
            f"""INSERT INTO {name} SELECT s.id,s.text FROM segments s JOIN snapshot_documents sd ON sd.extraction_id=s.extraction_id WHERE sd.snapshot_id=? ORDER BY s.id""",
            (snapshot_id,),
        )
